"use client";
import Link from "next/link";
import { ArrowLeft, Building2, Camera, MapPin, MapPinned } from "lucide-react";
import type { Area, Building, Governorate } from "@/lib/types";
import { useData } from "./data-provider";
import { Badge } from "./ui";
export function GovernorateCard({ item }: { item: Governorate }) { const { data } = useData(); const areas = data.areas.filter(a => a.governorateId === item.id); const buildings = data.buildings.filter(b => b.governorateId === item.id); return <article className="place-card"><div className="card-image"><img src={item.image} alt={`صورة محافظة ${item.name}`} loading="lazy"/><span><MapPinned size={15}/> محافظة</span></div><div className="card-body"><h3>{item.name}</h3><p>{item.description}</p><div className="card-stats"><span><b>{areas.length}</b> منطقة</span><span><b>{buildings.length}</b> عمارة</span></div><Link href={`/governorates/${item.id}`} className="card-link">استكشف المحافظة <ArrowLeft size={17}/></Link></div></article>; }
export function AreaCard({ item }: { item: Area }) { const { data } = useData(); const count = data.buildings.filter(b => b.areaId === item.id).length; return <article className="place-card"><div className="card-image"><img src={item.image} alt={`صورة منطقة ${item.name}`} loading="lazy"/><span><MapPin size={15}/> منطقة</span></div><div className="card-body"><h3>{item.name}</h3><p>{item.description}</p><div className="card-stats"><span><b>{count}</b> عمارة متاحة</span></div><Link href={`/governorates/${item.governorateId}/areas/${item.id}`} className="card-link">عرض العمارات <ArrowLeft size={17}/></Link></div></article>; }
export function BuildingCard({ item }: { item: Building }) { return <article className="building-card"><div className="card-image"><img src={item.mainImage} alt={`الواجهة الرئيسية لـ ${item.name}`} loading="lazy"/><Badge tone={item.details.deliveryStatus === "جاهز للاستلام" ? "green" : "gold"}>{item.details.deliveryStatus}</Badge><span className="photo-count"><Camera size={14}/>{item.images.length}</span></div><div className="card-body"><h3>{item.name}</h3><p className="location-line"><MapPin size={15}/>{item.address}</p><p>{item.description}</p><Link href={`/buildings/${item.id}`} className="card-link">عرض التفاصيل <ArrowLeft size={17}/></Link></div></article>; }
