"use client";
import Link from "next/link";
import { Building2, Eye, EyeOff, Map, MapPinned, Pencil, Plus, Search, Trash2, TrendingUp } from "lucide-react";
import { useMemo, useState } from "react";
import { useData } from "../data-provider";
import { Badge, ConfirmDialog, EmptyState } from "../ui";
import type { Area, Governorate } from "@/lib/types";
import { AdminShell } from "./admin-shell";
import { ImageUploadField } from "./image-upload-field";
export function AdminDashboard() { const { data } = useData(); const stats = [{label:"إجمالي المحافظات",value:data.governorates.length,icon:MapPinned,tone:"navy"},{label:"إجمالي المناطق",value:data.areas.length,icon:Map,tone:"gold"},{label:"إجمالي العمارات",value:data.buildings.length,icon:Building2,tone:"blue"},{label:"العمارات المنشورة",value:data.buildings.filter(x=>x.status==="published").length,icon:TrendingUp,tone:"green"}]; return <AdminShell title="نظرة عامة" subtitle="مرحبًا بك، إليك ملخص أداء الدليل العقاري اليوم."><div className="stat-grid">{stats.map(s => {const Icon=s.icon; return <article className="stat-card" key={s.label}><span className={`stat-icon ${s.tone}`}><Icon/></span><div><small>{s.label}</small><b>{s.value}</b><em>+12% هذا الشهر</em></div></article>})}</div><div className="admin-panels"><article className="admin-card"><div className="panel-head"><div><h2>آخر العمارات المضافة</h2><p>أحدث السجلات في قاعدة البيانات</p></div><Link href="/admin/buildings">عرض الكل</Link></div><div className="recent-list">{data.buildings.slice(0,5).map(b => <div key={b.id}><img src={b.mainImage} alt=""/><span><b>{b.name}</b><small>{data.areas.find(a=>a.id===b.areaId)?.name}</small></span><Badge tone={b.status === "published" ? "green" : "gray"}>{b.status === "published" ? "منشور" : "مخفي"}</Badge></div>)}</div></article><article className="admin-card quick-card"><div className="panel-head"><div><h2>إجراءات سريعة</h2><p>اختصارات لإدارة المحتوى</p></div></div><Link href="/admin/buildings/new"><Plus/><span><b>إضافة عمارة جديدة</b><small>أدخل التفاصيل وارفع الصور</small></span></Link><Link href="/admin/governorates"><MapPinned/><span><b>إدارة المحافظات</b><small>إضافة أو تعديل المحافظات</small></span></Link><Link href="/admin/areas"><Map/><span><b>إدارة المناطق</b><small>تنظيم المناطق داخل المحافظات</small></span></Link></article></div></AdminShell>; }

type GovForm = Pick<Governorate,"name"|"description"|"image">;
export function AdminGovernorates() { const { data, upsert, remove, toggle } = useData(); const [modal,setModal]=useState(false); const [editing,setEditing]=useState<Governorate|null>(null); const [form,setForm]=useState<GovForm>({name:"",description:"",image:""}); const [deleting,setDeleting]=useState<string|null>(null); const open=(item?:Governorate)=>{setEditing(item||null);setForm(item?{name:item.name,description:item.description,image:item.image}:{name:"",description:"",image:""});setModal(true)}; const save=()=>{if(!form.name.trim())return; upsert("governorates",{id:editing?.id||`gov-${Date.now()}`,slug:editing?.slug||`gov-${Date.now()}`,status:editing?.status||"published",...form,image:form.image||"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=900&q=80"});setModal(false)}; return <AdminShell title="المحافظات" subtitle="أضف المحافظات وعدّل بياناتها وحالة ظهورها." action={<button className="btn btn-gold" onClick={()=>open()}><Plus/> إضافة محافظة</button>}><AdminTableHead count={data.governorates.length}/><div className="table-wrap"><table><thead><tr><th>الصورة</th><th>اسم المحافظة</th><th>المناطق</th><th>العمارات</th><th>الحالة</th><th>الإجراءات</th></tr></thead><tbody>{data.governorates.map(g=><tr key={g.id}><td><img className="table-image" src={g.image} alt=""/></td><td><b>{g.name}</b></td><td>{data.areas.filter(a=>a.governorateId===g.id).length}</td><td>{data.buildings.filter(b=>b.governorateId===g.id).length}</td><td><Badge tone={g.status==="published"?"green":"gray"}>{g.status==="published"?"منشور":"مخفي"}</Badge></td><td><RowActions onEdit={()=>open(g)} onDelete={()=>setDeleting(g.id)} onToggle={()=>toggle("governorates",g.id)} hidden={g.status==="hidden"}/></td></tr>)}</tbody></table></div><EntityModal open={modal} title={editing?"تعديل المحافظة":"إضافة محافظة"} onClose={()=>setModal(false)} onSave={save}><label>اسم المحافظة<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="مثال: القاهرة"/></label><ImageUploadField value={form.image} onChange={image=>setForm({...form,image})} label="صورة المحافظة"/><label>وصف مختصر<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></EntityModal><ConfirmDialog open={!!deleting} onCancel={()=>setDeleting(null)} onConfirm={()=>{if(deleting)remove("governorates",deleting);setDeleting(null)}}/></AdminShell>; }

type AreaForm=Pick<Area,"name"|"description"|"image"|"governorateId">;
export function AdminAreas(){const{data,upsert,remove,toggle}=useData();const[modal,setModal]=useState(false);const[editing,setEditing]=useState<Area|null>(null);const[deleting,setDeleting]=useState<string|null>(null);const[form,setForm]=useState<AreaForm>({name:"",description:"",image:"",governorateId:data.governorates[0]?.id||""});const open=(item?:Area)=>{setEditing(item||null);setForm(item?{name:item.name,description:item.description,image:item.image,governorateId:item.governorateId}:{name:"",description:"",image:"",governorateId:data.governorates[0]?.id||""});setModal(true)};const save=()=>{if(!form.name||!form.governorateId)return;upsert("areas",{id:editing?.id||`area-${Date.now()}`,slug:editing?.slug||`area-${Date.now()}`,status:editing?.status||"published",...form,image:form.image||"https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80"});setModal(false)};return <AdminShell title="المناطق" subtitle="نظّم المناطق واربط كل منطقة بالمحافظة التابعة لها." action={<button className="btn btn-gold" onClick={()=>open()}><Plus/> إضافة منطقة</button>}><AdminTableHead count={data.areas.length}/><div className="table-wrap"><table><thead><tr><th>المنطقة</th><th>المحافظة</th><th>العمارات</th><th>الحالة</th><th>الإجراءات</th></tr></thead><tbody>{data.areas.map(a=><tr key={a.id}><td><div className="table-title"><img className="table-image" src={a.image} alt=""/><b>{a.name}</b></div></td><td>{data.governorates.find(g=>g.id===a.governorateId)?.name}</td><td>{data.buildings.filter(b=>b.areaId===a.id).length}</td><td><Badge tone={a.status==="published"?"green":"gray"}>{a.status==="published"?"منشور":"مخفي"}</Badge></td><td><RowActions onEdit={()=>open(a)} onDelete={()=>setDeleting(a.id)} onToggle={()=>toggle("areas",a.id)} hidden={a.status==="hidden"}/></td></tr>)}</tbody></table></div><EntityModal open={modal} title={editing?"تعديل المنطقة":"إضافة منطقة"} onClose={()=>setModal(false)} onSave={save}><label>اسم المنطقة<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>المحافظة<select value={form.governorateId} onChange={e=>setForm({...form,governorateId:e.target.value})}>{data.governorates.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><ImageUploadField value={form.image} onChange={image=>setForm({...form,image})} label="صورة المنطقة"/><label>الوصف<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></EntityModal><ConfirmDialog open={!!deleting} onCancel={()=>setDeleting(null)} onConfirm={()=>{if(deleting)remove("areas",deleting);setDeleting(null)}}/></AdminShell>}

export function AdminBuildings(){const{data,remove,toggle}=useData();const[q,setQ]=useState("");const[gov,setGov]=useState("");const[area,setArea]=useState("");const[status,setStatus]=useState("");const[deleting,setDeleting]=useState<string|null>(null);const filtered=useMemo(()=>data.buildings.filter(b=>(!q||b.name.includes(q))&&(!gov||b.governorateId===gov)&&(!area||b.areaId===area)&&(!status||b.status===status)),[data.buildings,q,gov,area,status]);return <AdminShell title="العمارات" subtitle="ابحث وصفِّ وأدر جميع العقارات من مكان واحد." action={<Link className="btn btn-gold" href="/admin/buildings/new"><Plus/> إضافة عمارة</Link>}><div className="filter-card"><label className="search-input"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث باسم العمارة..."/></label><select value={gov} onChange={e=>{setGov(e.target.value);setArea("")}}><option value="">كل المحافظات</option>{data.governorates.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><select value={area} onChange={e=>setArea(e.target.value)}><option value="">كل المناطق</option>{data.areas.filter(a=>!gov||a.governorateId===gov).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">كل الحالات</option><option value="published">منشور</option><option value="hidden">مخفي</option></select></div><AdminTableHead count={filtered.length}/>{filtered.length?<div className="table-wrap"><table><thead><tr><th>العمارة</th><th>المحافظة / المنطقة</th><th>الحالة</th><th>الصور</th><th>آخر تعديل</th><th>الإجراءات</th></tr></thead><tbody>{filtered.map(b=><tr key={b.id}><td><div className="table-title"><img className="table-image wide" src={b.mainImage} alt=""/><b>{b.name}</b></div></td><td><b className="cell-main">{data.governorates.find(g=>g.id===b.governorateId)?.name}</b><small className="cell-sub">{data.areas.find(a=>a.id===b.areaId)?.name}</small></td><td><Badge tone={b.status==="published"?"green":"gray"}>{b.status==="published"?"منشور":"مخفي"}</Badge></td><td>{b.images.length} صورة</td><td>{b.updatedAt}</td><td><RowActions viewHref={`/buildings/${b.id}`} editHref={`/admin/buildings/${b.id}/edit`} onDelete={()=>setDeleting(b.id)} onToggle={()=>toggle("buildings",b.id)} hidden={b.status==="hidden"}/></td></tr>)}</tbody></table></div>:<EmptyState/>}<ConfirmDialog open={!!deleting} onCancel={()=>setDeleting(null)} onConfirm={()=>{if(deleting)remove("buildings",deleting);setDeleting(null)}}/></AdminShell>}

function AdminTableHead({count}:{count:number}){return <div className="table-meta"><p><b>{count}</b> سجل</p><span>يتم حفظ التغييرات تلقائيًا على هذا الجهاز</span></div>}
function RowActions({onEdit,onDelete,onToggle,hidden,viewHref,editHref}:{onEdit?:()=>void;onDelete:()=>void;onToggle:()=>void;hidden:boolean;viewHref?:string;editHref?:string}){return <div className="row-actions">{viewHref&&<Link href={viewHref} aria-label="عرض"><Eye/></Link>}{editHref?<Link href={editHref} aria-label="تعديل"><Pencil/></Link>:<button onClick={onEdit} aria-label="تعديل"><Pencil/></button>}<button onClick={onToggle} aria-label={hidden?"نشر":"إخفاء"}>{hidden?<Eye/>:<EyeOff/>}</button><button className="delete" onClick={onDelete} aria-label="حذف"><Trash2/></button></div>}
function EntityModal({open,title,onClose,onSave,children}:{open:boolean;title:string;onClose:()=>void;onSave:()=>void;children:React.ReactNode}){if(!open)return null;return <div className="modal-backdrop" onMouseDown={onClose}><div className="entity-modal" onMouseDown={e=>e.stopPropagation()}><div><h2>{title}</h2><button onClick={onClose} aria-label="إغلاق">×</button></div><div className="modal-fields">{children}</div><footer><button className="btn btn-ghost" onClick={onClose}>إلغاء</button><button className="btn btn-gold" onClick={onSave}>حفظ البيانات</button></footer></div></div>}
