"use client";
import { Building2, CheckCircle2, ExternalLink, MapPin, MessageCircle, Phone, Send, StickyNote } from "lucide-react";
import { useData } from "../data-provider";
import { Breadcrumb } from "../breadcrumb";
import { Gallery } from "../gallery";
import { PublicShell } from "../layout/public-shell";
import { Badge } from "../ui";
export function BuildingPage({ id }: { id: string }) { const { data, ready } = useData(); const building = data.buildings.find(b => b.id === id); if (ready && !building) return <PublicShell><div className="container not-found"><Building2/><h1>العمارة غير موجودة</h1><p>ربما تم حذفها أو تغيير رابطها.</p></div></PublicShell>; if (!building) return <PublicShell><div className="container not-found"><p>جاري تحميل التفاصيل...</p></div></PublicShell>;
  const gov = data.governorates.find(g => g.id === building.governorateId); const area = data.areas.find(a => a.id === building.areaId);
  const detailRows = [["اسم العمارة",building.name],["المحافظة",gov?.name],["المنطقة",area?.name],["العنوان",building.address],["نوع العقار",building.details.propertyType],["عدد الأدوار",building.details.floors],["عدد الوحدات",building.details.units],["المساحات",building.details.area],["الغرف",building.details.rooms],["الحمامات",building.details.bathrooms],["حالة التشطيب",building.details.finishing],["حالة الاستلام",building.details.deliveryStatus]];
  return <PublicShell><section className="building-top"><div className="container"><Breadcrumb items={[{label:"المحافظات",href:"/governorates"},{label:gov?.name || "",href:`/governorates/${gov?.id}`},{label:area?.name || "",href:`/governorates/${gov?.id}/areas/${area?.id}`},{label:building.name}]}/><div className="building-title"><div><span className="kicker">عقار موثّق</span><h1>{building.name}</h1><p><MapPin size={17}/>{area?.name}، {gov?.name}</p></div><Badge tone="green"><CheckCircle2 size={15}/>{building.details.deliveryStatus}</Badge></div><Gallery images={building.images} title={building.name}/></div></section><section className="section details-section"><div className="container details-layout"><div className="details-main"><article className="info-card"><div className="info-title"><span><Building2/></span><div><h2>تفاصيل العمارة</h2><p>المواصفات والبيانات الأساسية</p></div></div><div className="detail-grid">{detailRows.map(([label,value]) => <div key={String(label)}><small>{label}</small><b>{value}</b></div>)}</div><div className="description-box"><h3>عن العمارة</h3><p>{building.description}</p></div></article><article className="info-card"><div className="info-title"><span><MapPin/></span><div><h2>اللوكيشن</h2><p>موقع العقار والطرق المحيطة</p></div></div><div className="map-placeholder"><div className="map-roads"><i/><i/><i/><span><MapPin/></span></div><div><b>{building.location.address}</b><small>{building.location.latitude}, {building.location.longitude}</small><a className="btn btn-navy" href={building.location.googleMapsUrl} target="_blank" rel="noreferrer">فتح في Google Maps <ExternalLink size={16}/></a></div></div></article><article className="info-card note-card"><div className="info-title"><span><StickyNote/></span><div><h2>ملاحظات</h2><p>معلومات إضافية مهمة</p></div></div><p>{building.notes}</p></article></div><aside className="contact-card"><span className="contact-icon"><Send/></span><h2>مهتم بهذا العقار؟</h2><p>تواصل مباشرة مع مسؤول العقار أو اطلب تحديد موعد للمعاينة.</p><div className="contact-number"><small>رقم التواصل</small><b dir="ltr">{building.contact.phone}</b></div><a className="btn btn-gold" href={`tel:${building.contact.phone}`}><Phone size={18}/> اتصل الآن</a><a className="btn btn-whatsapp" href={`https://wa.me/${building.contact.whatsapp}`} target="_blank" rel="noreferrer"><MessageCircle size={18}/> تواصل عبر WhatsApp</a><button className="btn btn-outline" onClick={() => alert("تم تسجيل طلب المعاينة وسيتواصل معك فريقنا قريبًا.")}>طلب معاينة</button><small className="contact-note"><CheckCircle2 size={14}/> لا توجد أي رسوم لطلب المعاينة</small></aside></div></section></PublicShell>;
}
