"use client";
import { Building2, MapPinned } from "lucide-react";
import { useData } from "../data-provider";
import { AreaCard, BuildingCard, GovernorateCard } from "../cards";
import { Breadcrumb } from "../breadcrumb";
import { PublicShell } from "../layout/public-shell";
import { EmptyState, SkeletonGrid } from "../ui";
function PageHero({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <section className="page-hero"><div className="container"><span>{eyebrow}</span><h1>{title}</h1><p>{text}</p></div></section>; }
export function GovernoratesPage() { const { data, ready } = useData(); return <PublicShell><PageHero eyebrow="دليل المحافظات" title="اكتشف العقارات في كل محافظة" text="تصفح محافظات مصر واختر وجهتك للوصول إلى المناطق والعمارات المتاحة."/><section className="section"><div className="container"><Breadcrumb items={[{ label: "المحافظات" }]}/>{ready ? <div className="card-grid">{data.governorates.filter(g => g.status === "published").map(g => <GovernorateCard key={g.id} item={g}/>)}</div> : <SkeletonGrid/>}</div></section></PublicShell>; }
export function GovernoratePage({ id }: { id: string }) { const { data, ready } = useData(); const gov = data.governorates.find(g => g.id === id); const areas = data.areas.filter(a => a.governorateId === id && a.status === "published"); if (ready && !gov) return <PublicShell><div className="container not-found"><MapPinned/><h1>المحافظة غير موجودة</h1><p>ربما تم حذفها أو تغيير رابطها.</p></div></PublicShell>; return <PublicShell>{gov && <PageHero eyebrow={`محافظة ${gov.name}`} title={`مناطق محافظة ${gov.name}`} text={gov.description}/>}<section className="section"><div className="container"><Breadcrumb items={[{label:"المحافظات",href:"/governorates"},{label:gov?.name || "..."}]}/><div className="result-head"><div><h2>اختر المنطقة</h2><p>{areas.length} منطقة متاحة للتصفح</p></div></div>{!ready ? <SkeletonGrid/> : areas.length ? <div className="card-grid">{areas.map(a => <AreaCard key={a.id} item={a}/>)}</div> : <EmptyState title="لا توجد مناطق منشورة"/>}</div></section></PublicShell>; }
export function AreaPage({ governorateId, areaId }: { governorateId: string; areaId: string }) { const { data, ready } = useData(); const gov = data.governorates.find(g => g.id === governorateId); const area = data.areas.find(a => a.id === areaId); const buildings = data.buildings.filter(b => b.areaId === areaId && b.status === "published"); return <PublicShell><PageHero eyebrow={`${gov?.name || "المحافظة"} • ${area?.name || "المنطقة"}`} title={`عمارات ${area?.name || "المنطقة"}`} text="قارن بين العمارات المتاحة، ثم افتح صفحة أي عمارة للاطلاع على الصور والتفاصيل الكاملة."/><section className="section"><div className="container"><Breadcrumb items={[{label:"المحافظات",href:"/governorates"},{label:gov?.name || "...",href:`/governorates/${governorateId}`},{label:area?.name || "..."}]}/><div className="result-head"><div><h2>العقارات المتاحة</h2><p>{buildings.length} نتيجة في هذه المنطقة</p></div><span className="result-icon"><Building2/></span></div>{!ready ? <SkeletonGrid/> : buildings.length ? <div className="card-grid">{buildings.map(b => <BuildingCard key={b.id} item={b}/>)}</div> : <EmptyState title="لا توجد عمارات منشورة في هذه المنطقة"/>}</div></section></PublicShell>; }
